Repository MacarenaRodriguez1993/Emme-3D, pull requests merged in 2022-12, with the labels that each got.

#8 Cosas básicas para el proyecto
  .prettierignore
  .prettierrc
  README.md
  api/index.js
  api/package.json
  client/.gitignore
Labels: enhancement

#19 Estructura básica del backend
  .gitignore
  api/README.md
  api/index.js
  api/middleware/index.js
  api/models/index.js
  api/package-lock.json
  api/routes/index.js
  client/package-lock.json
Labels: Back

#32 creación de componente NavBar
  client/package.json
  client/src/App.css
  client/src/App.jsx
  client/src/components/Footer.jsx
  client/src/components/Footer/Footer.jsx
  client/src/components/Footer/footer.css
  client/src/components/NavBar.jsx
  client/src/components/NavBar/NavBar.css
  client/src/components/NavBar/NavBar.jsx
  client/src/index.css
  client/src/main.jsx
  client/src/pages/home.css
  client/src/pages/home.jsx
Labels: Front

#38 Page products #2
  client/package.json
  client/src/App.css
  client/src/App.jsx
  client/src/assets/stitch.png
  client/src/components/Footer/Footer.jsx
  client/src/components/Footer/footer.css
  client/src/components/NavBar/NavBar.css
  client/src/components/NavBar/NavBar.jsx
  client/src/components/Product/product.css
  client/src/components/Product/product.jsx
  client/src/pages/Home/home.css
  client/src/pages/Home/home.jsx
  client/src/pages/Productos/products.css
  client/src/pages/Productos/products.jsx
  client/src/redux/actions/actions.js
  client/src/redux/reducer/index.js
Labels: Front

#39 Landing
  client/src/App.jsx
  client/src/assets/logo.png
  client/src/pages/Landing/landing.css
  client/src/pages/Landing/landing.jsx
Labels: Front

#37 Login
  client/package.json
  client/src/App.css
  client/src/assets/logo1.png
  client/src/index.css
  client/src/pages/Login.css
  client/src/pages/Login.jsx
Labels: Front

#33 Pau #7 - Modelos BBDD
  api/index.js
  api/models/Category.js
  api/models/Order.js
  api/models/OrderDetails.js
  api/models/OrderState.js
  api/models/Product.js
  api/models/Review.js
  api/models/User.js
  api/models/index.js
Labels: Back

#40 #7 fixes
  api/models/Category.js
  api/models/Order.js
  api/models/OrderDetails.js
  api/models/OrderState.js
Labels: BUG, Mejoras, Back

#43 metodo delete creado #31
  api/routes/index.js
  api/routes/productsRoute.js
Labels: Back

#60 Cristian filtros issues #3 y #14
  client/package.json
  client/src/App.jsx
  client/src/assets/emme3d-logo.png
  client/src/components/Footer/Footer.jsx
  client/src/components/ProductsContainer/ProductsContainer.css
  client/src/components/ProductsContainer/ProductsContainer.jsx
  client/src/components/SearchFilters/SearchFilters.css
  client/src/components/SearchFilters/SearchFilters.jsx
  client/src/redux/actions/actions.js
  client/src/redux/reducer/index.js
Labels: Front

#63 actualizando estilos de landing y products
  client/src/App.css
  client/src/components/NavBar/NavBar.css
  client/src/components/NavBar/NavBar.jsx
  client/src/pages/Landing/landing.css
  client/src/pages/Landing/landing.jsx
  client/src/pages/Productos/products.css
Labels: Front

#62 Obtener detalles producto por /:id #45
  api/controllers/productController.js
  api/middleware/middlewareProducts.js
  api/routes/products.js
Labels: Back

#66 implemento componente filtros
  client/src/pages/Productos/products.jsx
Labels: Front

#64 Obtener lista de categorías #47
  api/controllers/categoryController.js
  api/middleware/middlewareCategories.js
  api/routes/categories.js
Labels: Back

#68 Detalle #25
  client/package.json
  client/src/App.jsx
  client/src/assets/carrito.png
  client/src/assets/naruto1.png
  client/src/components/Footer/Footer.jsx
  client/src/components/Footer/footer.css
  client/src/components/NavBar/NavBar.css
  client/src/pages/Details/Details.css
  client/src/pages/Details/Details.jsx
  client/src/pages/Login/Login.css
  client/src/pages/Login/Login.jsx
  client/src/pages/css/home.css
  client/src/pages/css/home.jsx
  client/src/redux/actions/actions.js
  client/src/redux/reducer/index.js
Labels: Front

#70 Crear nueva categoría #48
  api/controllers/categoryController.js
  api/middleware/middlewareCategories.js
  api/routes/categories.js
Labels: Back

#71 Editar categoría existente #49
  api/controllers/categoryController.js
  api/middleware/middlewareCategories.js
  api/routes/categories.js
Labels: Back

#72 Borrar categoría #50
  api/controllers/categoryController.js
  api/middleware/middlewareCategories.js
  api/routes/categories.js
Labels: Back

#74 Rutas marcos put
  api/controllers/productController.js
  api/index.js
  api/middleware/middlewareProducts.js
  api/routes/products.js
Labels: Documentación, Back

#75 Crear producto #6
  api/controllers/productController.js
  api/middleware/middlewareProducts.js
  api/routes/products.js
Labels: Back

#76 busqueda por query name arreglada, creditos a alex
  api/controllers/productController.js
  api/middleware/middlewareProducts.js
  api/routes/products.js
Labels: Back

#81 Page products #2
  client/src/pages/Productos/products.jsx
  client/src/redux/actions/actions.js
Labels: Front

#85 Reparacion de la pagina de detalles
  client/package.json
  client/src/App.css
  client/src/App.jsx
  client/src/components/CreateProduct/CreateProduct.css
  client/src/components/CreateProduct/CreateProduct.jsx
  client/src/components/NavBar/NavBar.css
  client/src/components/NavBar/NavBar.jsx
  client/src/pages/Details/Details.css
  client/src/pages/Details/Details.jsx
  client/src/pages/Landing/landing.css
  client/src/pages/Productos/products.css
  client/src/pages/Productos/products.jsx
  client/src/redux/actions/actions.js
Labels: Front

#86 Search#42
  client/src/components/SearchByName/searchByName.css
  client/src/components/SearchByName/searchByName.jsx
  client/src/pages/Productos/products.css
  client/src/pages/Productos/products.jsx
  client/src/redux/actions/actions.js
  client/src/redux/reducer/index.js
Labels: Front

#87 estilo letras landing y navbar
  client/src/components/NavBar/NavBar.css
  client/src/pages/Landing/landing.css
  client/src/pages/Landing/landing.jsx
Labels: Front

#88 se agrego estilos a la pageProducts
  client/src/components/Product/product.css
  client/src/components/Product/product.jsx
  client/src/pages/Productos/products.css
  client/src/pages/Productos/products.jsx
Labels: Front

#89 se agrego funcionalidad al boton delete
  client/src/components/Product/product.jsx
  client/src/pages/Productos/products.css
  client/src/pages/Productos/products.jsx
  client/src/redux/actions/actions.js
  client/src/redux/reducer/index.js
Labels: Front

#101 Editar producto#83
  client/src/App.jsx
  client/src/components/CreateProduct/CreateProduct.jsx
  client/src/components/Product/product.jsx
  client/src/redux/actions/actions.js
  client/src/redux/reducer/index.js
Labels: Front

#95 Relación Producto-Categorias
  api/controllers/productController.js
  api/middleware/middlewareProducts.js
  client/src/components/CrearProducto.jsx
  client/src/components/CreateProduct/CreateProduct.jsx
Labels: Back

#102 deploy front
  client/src/main.jsx
  client/src/redux/actions/actions.js
Labels: Front

#105 ruta getAllUsers
  api/controllers/userController.js
  api/middleware/middlewareUsers.js
  api/routes/users.js
Labels: Back

#104 se creo ruta post crearUsuario
  api/controllers/userController.js
  api/middleware/middlewareUsers.js
  api/models/User.js
  api/routes/users.js
Labels: Back

#108 se creo ruta delete con borrado logico
  api/controllers/userController.js
  api/middleware/middlewareUsers.js
  api/routes/users.js
Labels: Back

#106 #103 cosas que cambiar de la week 1
  api/controllers/orderDetailsController.js
  api/controllers/productController.js
  api/models/OrderDetails.js
  api/models/Product.js
Labels: Mejoras, Back

#109 icono whatsapp
  client/src/components/Footer/Footer.jsx
  client/src/components/Footer/footer.css
Labels: Front

#113 carrito terminado, algunos bugs pero se puede arreglar mas tarde
  api/package.json
  api/routes/index.js
  api/routes/mercadopago.js
  client/package.json
  client/src/App.jsx
  client/src/components/NavBar/NavBar.jsx
  client/src/main.jsx
  client/src/pages/Cart/Cart.css
  client/src/pages/Cart/Cart.jsx
  client/src/pages/Details/Details.jsx
  client/src/redux/actions/actions.js
  client/src/redux/reducer/index.js
  client/src/redux/store/store.js
Labels: Back, Front

#114 Detalle #25
  client/src/App.jsx
  client/src/pages/Login/Login.jsx
  client/src/pages/Login/LoginGoogle.jsx
  client/src/pages/perfil/Perfil.jsx
Labels: Front
