Repository MacarenaRodriguez1993/Emme-3D, pull requests merged in 2023-01, with the labels that each got.

#115 99 notificaciones por mail
  api/controllers/emailController.js
  api/package.json
  api/routes/email.js
  api/routes/index.js
  client/src/pages/register/Register.jsx
  client/src/redux/actions/actions.js
Labels: Back

#117 Boton comprar
  client/src/pages/Cart/Cart.css
  client/src/pages/Cart/Cart.jsx
Labels: Front

#116 se cambio codigo para poder actualizar productos
  client/src/App.jsx
  client/src/components/CreateProduct/CreateProduct.jsx
  client/src/validations/validations-form.js
Labels: Front

#128 Fixed product details category
  api/controllers/productController.js
  client/src/pages/Details/Details.jsx
Labels: BUG, Back, Front

#130 Cristian carrusel imgs
  client/package.json
  client/src/components/Carousel/Carousel.jsx
  client/src/components/CreateProduct/CreateProduct.jsx
  client/src/pages/Details/Details.jsx
  client/src/redux/actions/actions.js
  client/src/redux/reducer/index.js
Labels: Front

#138 53 y 51
  api/controllers/orderController.js
  api/controllers/userController.js
  api/index.js
  api/middleware/middlewareOrders.js
  api/middleware/middlewareUsers.js
  api/models/Order.js
  api/routes/index.js
  api/routes/orders.js
  client/src/components/CrearProducto.jsx
Labels: Back

#139 21 crear componente home
  client/src/App.jsx
  client/src/pages/Home/home.css
  client/src/pages/Home/home.jsx
Labels: Front

#141 Panel de usuario
  api/models/User.js
  client/src/components/UserPanel/UserPanel.css
  client/src/components/UserPanel/UserPanel.jsx
  client/src/redux/actions/actions.js
Labels: Back, Front

#142 Rutas y actions para USUARIOS
  api/controllers/userController.js
  api/index.js
  api/models/User.js
  api/routes/users.js
  client/src/components/UserPanel/UserPanel.jsx
  client/src/pages/Login/Login.jsx
  client/src/pages/Login/LoginGoogle.jsx
  client/src/pages/register/Register.jsx
  client/src/redux/actions/actions.js
  client/src/redux/reducer/index.js
Labels: Back, Front

#143 Cristian panel usuario
  api/index.js
  client/src/components/UserPanel/UserPanel.css
  client/src/components/UserPanel/UserPanel.jsx
  client/src/pages/perfil/Perfil.jsx
  client/src/redux/actions/actions.js
Labels: Front

#153 Fix filtros
  client/src/redux/reducer/index.js
Labels: Front

#154 Conexión back front carrito
  api/routes/mercadopago.js
  api/routes/orders.js
  client/src/App.jsx
  client/src/pages/Cart/Cart.jsx
  client/src/pages/Successfull/successfulOrder.css
  client/src/pages/Successfull/successfulOrder.jsx
  client/src/redux/actions/actions.js
Labels: Front

#155 Auth context
  client/src/App.jsx
  client/src/components/Carousel/Carousel.css
  client/src/components/NavBar/NavBar.jsx
  client/src/components/Product/product.jsx
  client/src/components/UserPanel/UserPanel.jsx
  client/src/components/context/AuthContext.jsx
  client/src/components/context/PrivateRoutes.jsx
  client/src/components/context/PublicRoutes.jsx
  client/src/main.jsx
  client/src/pages/Details/Details.jsx
  client/src/pages/Login/Login.jsx
  client/src/pages/Login/LoginGoogle.jsx
  client/src/pages/perfil/Perfil.jsx
  client/src/pages/register/Register.jsx
  client/src/redux/actions/actions.js
  client/src/redux/reducer/index.js
  client/src/redux/store/store.js
Labels: BUG, Front

#168 146 crear pagina contacto
  api/controllers/emailController.js
  api/routes/email.js
  client/package.json
  client/src/App.jsx
  client/src/components/NavBar/NavBar.jsx
  client/src/pages/Contacto/contacto.css
  client/src/pages/Contacto/contacto.jsx
  client/src/redux/actions/actions.js
Labels: Front

#172 Auth context
  api/controllers/userController.js
  api/middleware/middlewareUsers.js
  api/models/User.js
  api/routes/users.js
  client/src/App.css
  client/src/App.jsx
  client/src/components/NavBar/NavBar.css
  client/src/components/NavBar/NavBar.jsx
  client/src/components/UserPanel/UserPanel.jsx
  client/src/pages/Login/Login.jsx
  client/src/pages/Login/LoginGoogle.jsx
  client/src/pages/register/Register.jsx
  client/src/redux/actions/actions.js
  client/src/redux/reducer/index.js
Labels: Back, Front

#173 Pagenosotros
  client/src/App.jsx
  client/src/assets/person.jpg
  client/src/pages/About/about.css
  client/src/pages/About/about.jsx
Labels: Front

#170 Conexión back front carrito
  api/controllers/orderController.js
  api/models/Order.js
  api/routes/mercadopago.js
  client/package.json
  client/src/App.jsx
  client/src/components/ShoppingCart/ShoppingCart.css
  client/src/components/ShoppingCart/ShoppingCart.jsx
  client/src/pages/Cart/Cart.jsx
  client/src/pages/Successfull/successfulOrder.jsx
  client/src/redux/actions/actions.js
  client/src/redux/reducer/index.js
Labels: Back, Front

#174 Corrección de errores
  api/routes/mercadopago.js
  client/src/pages/Cart/Cart.jsx
Labels: BUG, Back

#175 Imagen de producto correcta
  client/src/pages/Cart/Cart.jsx
Labels: BUG, Front

#178 177 mensajes interactivos con toastify
  api/controllers/userController.js
  client/package.json
  client/src/components/CreateProduct/CreateProduct.jsx
  client/src/components/Product/product.jsx
  client/src/components/UserPanel/UserPanel.jsx
  client/src/pages/Contacto/contacto.jsx
  client/src/pages/Details/Details.jsx
  client/src/pages/Login/Login.jsx
  client/src/pages/Login/LoginGoogle.jsx
  client/src/pages/perfil/Perfil.jsx
Labels: Mejoras, Front

#181 Conexión back front carrito
  api/controllers/orderController.js
  api/middleware/middlewareProducts.js
  api/models/Order.js
  api/routes/orders.js
  api/routes/products.js
  client/src/pages/Successfull/successfulOrder.jsx
Labels: Back, Front

#185 Obtener lista de los pedidos del usuario actual #52
  api/controllers/orderController.js
Labels: Back

#187 182 mejoras front
  client/package.json
  client/src/Admin/components/Topbar/Topbar.css
  client/src/Admin/components/Topbar/Topbar.jsx
  client/src/components/Carousel/Carousel.css
  client/src/components/ImageCarousel/ImageCarousel.jsx
  client/src/components/NavBar/NavBar.jsx
  client/src/pages/Productos/products.css
  client/src/pages/Productos/products.jsx
  client/src/redux/actions/actions.js
Labels: Front

#183 Auth context
  client/src/App.jsx
  client/src/components/LoginModal/ModalLogin.css
  client/src/components/LoginModal/ModalLogin.jsx
  client/src/components/context/AuthContext.jsx
  client/src/pages/Cart/Cart.jsx
  client/src/pages/Login/Login.css
  client/src/pages/Login/Login.jsx
  client/src/pages/Login/LoginGoogle.jsx
  client/src/pages/register/Register.jsx
  client/src/redux/actions/actions.js
Labels: Front

#186 Editar pedidos (solo admin) #54
  api/controllers/orderController.js
Labels: Back

#190 reviews
  api/controllers/reviewController.js
  api/models/Review.js
  client/package.json
  client/src/components/LoginModal/ModalLogin.css
  client/src/components/LoginModal/ModalLogin.jsx
  client/src/components/context/AuthContext.jsx
  client/src/pages/Details/Details.css
  client/src/pages/Details/Details.jsx
  client/src/redux/actions/actions.js
Labels: Back, Front

#191 Auth context
  client/src/pages/Details/Details.jsx
  client/src/redux/actions/actions.js
Labels: Front

#200 se arreglo un error en la edicion de un usuario
  client/src/Admin/pages/Userlist/Userlist.jsx
  client/src/Admin/pages/user/User.jsx
Labels: BUG

#203 bugs user resuelto
  client/src/Admin/pages/user/User.jsx
  client/src/redux/actions/actions.js
  client/src/redux/reducer/index.js
Labels: Front

#206 deslogueo arreglado
  client/src/redux/actions/actions.js
  client/src/redux/reducer/index.js
Labels: Front
